volumes:
  postgres_data:
  postgres_backups:
  web_uv_cache:

services:
  postgres:
    image: "postgres:16-bookworm"
    container_name: datatables_django_widget_datatables_django_widgetlocal_postgres
    env_file:
      - ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups

  django:
    build:
      context: ./app
    depends_on:
      - postgres
    volumes:
      - ./app:/app:z
      - web_uv_cache:/usr/local/bin/uv_cache
    env_file:
      - ./app/.env
    ports:
      - '8080:8080'
    command: /start
